#pragma once

typedef enum EN_GAMEPARTICLETYPE
{
	GAMEPARTICLETYPE_SNOW,
	GAMEPARTICLETYPE_EXPLOSION,
	GAMEPARTICLETYPE_SPRINKLE,
	GAMEPARTICLETYPE_SUN,
	GAMEPARTICLETYPE_BLAZE,
	GAMEPARTICLETYPE_METEOR,
	GAMEPARTICLETYPE_TRACE,
	GAMEPARTICLETYPE_END

}GAMEPARTICLETYPE;
