#pragma once

typedef enum EN_PHYSICSSHAPETYPE
{
	PHYSICSSHAPETYPE_SPHERE, // 구 모양
	PHYSICSSHAPETYPE_RECTOSAHEDRON, // 직육면체 모양
	//PHYSICSSHAPETYPE_CYLINDER, // 원기둥 모양(미구현)
	//PHYSICSSHAPETYPE_POLYHEDRON, // 다면체 모양(미구현)
	PHYSICSSHAPETYPE_END
}PHYSICSSHAPETYPE;

typedef enum EN_PHYSICSBODYTYPE
{
	PHYSICSBODYTYPE_STATIC, // 고정되어있음
	PHYSICSBODYTYPE_DINAMIC, // 충돌에 영향을받아 움직임
	PHYSICSBODYTYPE_END
}PHYSICSBODYTYPE;