#pragma once

typedef enum EN_GRIDBOXKIND
{
	GRIDBOXKIND_NONE,    // 박스가 없는 지점
	GRIDBOXKIND_DEFAULT, // 텍스쳐 씌우고, 오토 높이맵에도 어느정도 영향있을거임 (물일경우 체크를 안한다던지)
	GRIDBOXKINE_BLOCK1,
	GRIDBOXKINE_BLOCK2,
	GRIDBOXKINE_GRASS,
	GRIDBOXKINE_MARBLE,
	GRIDBOXKINE_ROCK,
	GRIDBOXKINE_SOIL,
	GRIDBOXKINE_WOODEN,
	GRIDBOXKIND_END
}GRIDBOXKIND;